server:
  port: 10088
  ssl:
    key-store: ./pfx/3878946_www.wavab.cn.pfx
    key-store-password: WHCKts3t
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 996649855
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    favicon:
      enabled: true
    static-path-pattern: /static/**
mybatis:
  type-aliases-package: com.wb.dao
logging:
  level:
   com:
    wb:
     dao: debug
